import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Epilogue } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";
import "./styles.css";
import { ChevronUp, Facebook, Instagram, Linkedin } from "lucide-react";
import Header from "@/components/Header";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nav = [
    {
      link: "/",
      title: "Home",
    },
    {
      link: "",
      title: "Find a Lawyer",
    },
    {
      link: "",
      title: "Legal Services",
    },
    {
      link: "",
      title: "Legal Forum",
    },
    {
      link: "",
      title: "Law Firms",
    },
    {
      link: "",
      title: "Insights",
    },
    {
      link: "",
      title: "About",
    },
    {
      link: "",
      title: "Contact",
    },
    {
      link: "",
      title: "For Lawyers",
    },
    {
      link: "",
      title: "Authors",
    },
  ];
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${epilogue.variable} antialiased`}>
        <Header />
        {children}

        <footer className="mt-12">
          <div className="container">
            <Image
              src="/images/logo.webp"
              alt=""
              width={250}
              height={250}
              className="mx-auto"
            />

            <nav className="mt-8">
              <ul className="flex flex-col items-center justify-center text-center gap-4">
                {nav.map((item, key) => (
                  <li className="font-medium text-teal-900" key={key}>
                    <Link href={item.link}>{item.title}</Link>
                  </li>
                ))}
              </ul>
            </nav>

            <div className="relative flex items-center justify-center w-full my-8">
              <div className="absolute w-full border-t border-teal-600"></div>

              <Link href="#" className="z-10">
                <div className="p-1 rounded-full bg-teal-600">
                  <ChevronUp color="oklch(98.4% 0.014 180.72)" />
                </div>
              </Link>
            </div>

            <div className="flex items-center justify-center gap-3">
              <Link href="">
                <Facebook size={20} />
              </Link>
              <Link href="">
                <Instagram size={20} />
              </Link>
              <Link href="">
                <Linkedin size={20} />
              </Link>
            </div>

            <div className="my-6 text-sm text-center">
              &copy; {new Date().getFullYear()} Proudly Powered by Connect
              Legal.
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
