import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Epilogue } from "next/font/google";
import "./globals.css";
import "./styles.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

const epilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${epilogue.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
